#!/bin/sh

echo CURRENT_VERSION=TAG

docker pull bertbaron/ansible
docker run --rm -ti -v $(dirname "$0"):/workdir bertbaron/ansible setup

echo "Pulling the latest image for TAG"
docker pull bertbaron/ansible:TAG
echo
